# app/Dockerfile
FROM python:3.10.1-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && apt-get clean

# Install dependencies
COPY ../backend-requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r backend-requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]