shortforms = {
    "a/p": "anterior-posterior",
    "a/w": "associated with",
    "b/l": "bilateral",
    "b/p": "blood pressure",
    "c/b": "casebook (sometimes chartbook)",
    "c/c": "chief complaint",
    "c/d": "clean and dry",
    "c/e": "clinical evaluation",
    "c/f": "comes for (follow-up)",
    "c/o": "complains of",
    "c/w": "consistent with",
    "d/c": "discontinue or discharge",
    "d/o": "disease of",
    "d/t": "due to",
    "e/o": "evidence of",
    "f/b": "followed by",
    "f/c": "fever and chills",
    "f/u": "follow-up",
    "g/r": "general rule",
    "h/h": "hand hygiene",
    "h/o": "history of",
    "i/j": "icteric jaundice",
    "i/o": "intake/output",
    "m/g": "milligrams",
    "m/r": "medical records",
    "n/a": "not applicable",
    "n/v": "nausea and vomiting",
    "p/w": "presents with",
    "r/g": "rule out",
    "r/o": "rule out",
    "r/r": "respiration rate",
    "s/p": "status post",
    "s/s": "signs and symptoms",
    "u/a": "urinalysis",
    "u/l": "upper limb",
    "u/s": "ultrasound",
    "w/c": "wheelchair",
    "w/o": "without",
    "w/r": "with respect to",
    "y/o": "years old"
}