name: Build and Push FAST API application Docker Image to GCP

on:
  push:
    paths:
      - 'app/**'
    branches:
      - feature/deploy
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCP SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -f app/Dockerfile --platform linux/amd64 -t us-docker.pkg.dev/gcr.io/medscript-437117/fast-api-app:latest .

    - name: Push Docker image to Container Registry
      run: |
        docker push us-docker.pkg.dev/gcr.io/medscript-437117/fast-api-app:latest
