name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "dev-girish"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "medscript"
        options: >-
          --health-cmd "pg_isready -U dev-girish" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      DB_USER: "dev-girish"
      DB_PASS: "password"
      DB_NAME: "medscript"
      DB_HOST: "localhost"
      DB_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the same version as your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Tests
        run: |
          # Run pytest to test all unit tests and check coverage
          pytest tests/unit --cov=app --cov-report=xml --disable-warnings
