name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - feature/*
      - bug-fixes/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }} 
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }} 
        options: >-
          --health-cmd "pg_isready -U test-dev" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT}}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY}}
      JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH  
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          # Run pytest to test all unit tests and check coverage
          pytest tests/unit --cov=app --cov-report=xml --disable-warnings
