name: Deploy to Cloud Run

on:
  push:
    branches:
      - feature/UI-deploy
    paths:
      - 'UI/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: medscript-437117
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Build Docker image
        run: |
          cd UI
          docker build -t gcr.io/medscript-437117/streamlit-app:latest .

      - name: Push Docker image to GCR
        run: |
          gcloud auth configure-docker gcr.io
          docker push gcr.io/medscript-437117/streamlit-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-app \
            --image gcr.io/medscript-437117/streamlit-app:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
