name: Deploy Streamlit App to GCP

on:
  push:
    paths:
      - 'UI/**'
    branches:
      - feature/UI-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure Docker for Google Cloud
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/medscript-437117/streamlit-app:latest .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/medscript-437117/streamlit-app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy streamlit-app \
          --image gcr.io/medscript-437117/streamlit-app:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
